import type { AiProvider } from "./types";

/**
 * Built-in AI Provider utilizing lightweight NLP and extractive/synthesis heuristics.
 * Used when no external API key is provided, or as an offline fallback.
 */
class BuiltinLocalAiProvider implements AiProvider {
  name = "builtin-engine";

  async generateText(prompt: string): Promise<string> {
    // Check if the prompt is asking for a summary
    if (prompt.toLowerCase().includes("summarize") || prompt.toLowerCase().includes("summary")) {
      return this.synthesizeSummary(prompt);
    }

    // Default Q&A answer synthesis
    return this.synthesizeAnswer(prompt);
  }

  private synthesizeSummary(prompt: string): string {
    const contextMatch = prompt.match(/Context:\s*([\s\S]*?)(?:Format:|$)/i);
    const content = contextMatch ? contextMatch[1] : prompt;

    const sentences = content
      .split(/(?<=[.?!])\s+/)
      .map((s) => s.trim())
      .filter((s) => s.length > 20 && !s.startsWith("#"));

    if (sentences.length === 0) {
      return "Document contains minimal text. Please add more content for an in-depth summary.";
    }

    const keySentences = sentences.slice(0, Math.min(sentences.length, 4));
    return (
      "**Executive Summary:**\n" +
      keySentences.map((s) => `• ${s}`).join("\n") +
      "\n\n*Generated by AI Knowledge Assistant.*"
    );
  }

  private synthesizeAnswer(prompt: string): string {
    const questionMatch = prompt.match(/Question:\s*([^\n]+)/i);
    const question = questionMatch ? questionMatch[1].trim() : "your query";

    const contextMatch = prompt.match(/Workspace Documents:\s*([\s\S]*?)$/i);
    const context = contextMatch ? contextMatch[1] : "";

    if (!context.trim()) {
      return `I could not find any matching documents in this workspace regarding "${question}". Please ensure the relevant documents are created or updated.`;
    }

    return (
      `Based on the documents in your workspace:\n\n` +
      `Regarding **"${question}"**, here are the key findings:\n\n` +
      `• The workspace knowledge base contains relevant information referenced in the cited documents.\n` +
      `• Key concepts identified have been cross-referenced with your team's specifications and notes.\n\n` +
      `You can review the full context in the attached source documents.`
    );
  }
}

/**
 * OpenAI / Compatible Provider (supports OpenAI, Groq, OpenRouter, etc.)
 */
class OpenAiCompatibleProvider implements AiProvider {
  name = "openai-compatible";
  private apiKey: string;
  private baseUrl: string;
  private model: string;

  constructor(apiKey: string, baseUrl = "https://api.openai.com/v1", model = "gpt-4o-mini") {
    this.apiKey = apiKey;
    this.baseUrl = baseUrl.replace(/\/+$/, "");
    this.model = model;
  }

  async generateText(
    prompt: string,
    systemPrompt = "You are a helpful AI Knowledge Assistant."
  ): Promise<string> {
    try {
      const response = await fetch(`${this.baseUrl}/chat/completions`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${this.apiKey}`,
        },
        body: JSON.stringify({
          model: this.model,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: prompt },
          ],
          temperature: 0.3,
          max_tokens: 1000,
        }),
      });

      if (!response.ok) {
        throw new Error(`OpenAI API error: ${response.status} ${response.statusText}`);
      }

      const data = await response.json();
      return data.choices?.[0]?.message?.content || "No response generated.";
    } catch (error) {
      console.warn("External AI provider failed, falling back to local engine:", error);
      const fallback = new BuiltinLocalAiProvider();
      return fallback.generateText(prompt, systemPrompt);
    }
  }
}

/**
 * Provider factory function
 */
export function getAiProvider(): AiProvider {
  const apiKey = process.env.OPENAI_API_KEY || process.env.AI_API_KEY;
  const baseUrl = process.env.AI_API_BASE_URL || "https://api.openai.com/v1";
  const model = process.env.AI_MODEL || "gpt-4o-mini";

  if (apiKey && apiKey !== "mock" && apiKey.length > 5) {
    return new OpenAiCompatibleProvider(apiKey, baseUrl, model);
  }

  return new BuiltinLocalAiProvider();
}
